language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - "yarn global add xo"
  - "yarn global add npx"

install:
  - NODE_ENV=development yarn

script:
  - cd server && yarn xo:lint