language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - "yarn global add xo"
  - "yarn global add npx"

install:
  - cd server && yarn && cd ..
  - cd client && yarn && cd ..

script:
  - cd server && yarn xo:lint && cd ..
  - cd client && yarn test && cd ..