version: "3"

services:
  backend:
    image: core
    container_name: biphub:latest
    build:
      context: ./server
      dockerfile: ../.docker/main.dockerfile
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules