version: "3"

services:
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: .nginx/nginx.dockerfile
    ports:
      - "80:80"
    environment:
       - NGINX_PORT=80
    depends_on:
      - frontend
      - backend
  backend:
    image: core
    container_name: biphub_backend
    build:
      context: .
      dockerfile: .docker/main.dockerfile
      args:
        SRC: ./server
    volumes:
      - ./server:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "3000:3000"
  frontend:
    image: client
    container_name: biphub_frontend
    build:
      context: .
      dockerfile: .docker/main.dockerfile
      args:
        SRC: ./client
    volumes:
      - ./client:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - backend