"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var userController = require("../../controllers/user.controller");
var passportConfig = require("../../config/passport.config");
exports.default = function () {
    var api = express_1.Router();
    api.get('/account', passportConfig.isAuthenticated, userController.getAccount);
    api.post('/account/profile', passportConfig.isAuthenticated, userController.postUpdateProfile);
    api.post('/account/password', passportConfig.isAuthenticated, userController.postUpdatePassword);
    api.post('/account/delete', passportConfig.isAuthenticated, userController.postDeleteAccount);
    api.get('/account/unlink/:provider', passportConfig.isAuthenticated, userController.getOauthUnlink);
    api.get('/account/login', userController.getLogin);
    api.post('/account/login', userController.postLogin);
    api.get('/account/logout', userController.logout);
    api.get('/account/forgot', userController.getForgot);
    api.post('/account/forgot', userController.postForgot);
    api.get('/account/reset/:token', userController.getReset);
    api.post('/account/reset/:token', userController.postReset);
    api.get('/account/signup', userController.getSignup);
    api.post('account//signup', userController.postSignup);
    return api;
};
